### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by betatester3016** [micahg/plugin.video.cbc#10] opened 2021-05-21 04:28 UTC
Hi,

Would it be possible to build in support for [IPTV Manager](https://github.com/add-ons/service.iptv.manager/wiki/Supported-Addons)?

**Comment by micahg** [comment] 2021-05-21 12:38
Hey,

Please let me look into what is required...

**Comment by betatester3016** [comment] 2021-05-21 14:48
Thank you for looking into this.

**Comment by micahg** [comment] 2021-05-21 14:53
Hey -- I never even knew that service existed and it looks amazing. Do you code? If so by all means feel free to contribute, otherwise, i have a few other projects I need to get done before I can add this -- but it looks awesome and I *do* want to do it.

**Comment by betatester3016** [comment] 2021-05-21 17:34
Sorry I don't code. I am more of a troubleshooter / tester / repository maintainer. At best I do some scripting. 

I use the CBC addon maintained by you frequently and thought it might be interesting to have the IPTV Manager feature added sometime in the future.

**Comment by micahg** [comment] 2021-05-21 18:47
No worries -- its on my radar -- I'd like to make it happen.

**Comment by betatester3016** [comment] 2021-06-19 18:22
Hi Micah,

I had a look at the code and it's way above my skill level. The best I can do (I know it's not much) is script the Kodi configuration interface.

**Comment by micahg** [comment] 2021-08-31 01:20
Hi @betatester3016,

I added it in 4.0.8, which is available from my repo: https://github.com/micahg/repo.micahg.

Warning, there seems to be a significant performance issue on my firestick when you enable iptv simple/iptv manager/cbc -- i'm trying to work out where the problem is (starting over here: https://github.com/kodi-pvr/pvr.iptvsimple/issues/550) but if you want to give it a try on your system, please go nuts. Once I figure out the performance issue I'll push it to the main kodi addons repo.

**Comment by betatester3016** [comment] 2021-08-31 13:35
Hi Micah

I tried on my Nvidia Shield Pro and compared to the Samsung TV addon, the
CBC addon takes longer to load the live stream.

Samsung TV addon load time: 1 sec
CBC addon load time: 4 sec

I also noticed the channel description in the EPG guide isn't being
populated, but let's tackle one thing at a time.

**Comment by betatester3016** [comment] 2021-08-31 13:42
Hi @micahg 

I tried on Nvidia Shield Pro and compared to the Samsung TV Plus and Pluto TV addons, the CBC addon takes longer to load the live stream via EPG.

Samsung TV Plus addon load time: 1 sec
Pluto TV addon load time: 1 sec
CBC addon load time:  4 sec

**Comment by micahg** [comment] 2021-08-31 13:44
Your samsung TV has EPG data!?

Any chance you know where they're getting it? I'm reverse engineering
the GEM app, and they don't have a guide.  CBC *does* have a guide,
but its in HTML and I'd rather not use beautiful soup.

About the slowness, I agree - it's slow. I am not 100% sure if I can
improve on that since afaik, once I hand the stream over to Kodi it is
out of my hands.

On Tue, Aug 31, 2021 at 9:42 AM betatester3016 ***@***.***> wrote:
>
> Hi @micahg
>
> I tried on Nvidia Shield Pro and compared to the Samsung TV Plus and Pluto TV addons, the CBC addon takes longer to load the live stream via EPG.
>
> Samsung TV Plus addon load time: 1 sec
> Pluto TV addon load time: 1 sec
> CBC addon load time: 4 sec
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
"The mark of an immature man is that he wants to die nobly for a
cause, while the mark of the mature man is that he wants to live
humbly for one."   --W. Stekel

**Comment by micahg** [comment] 2021-08-31 17:05
Performance issues resolved with a PVR cache clear (from settings).

**Comment by micahg** [comment] 2021-08-31 17:05
... anyway... if you can find a json or xml cbc epg feed I'd integrate
it *for sure*....

On Tue, Aug 31, 2021 at 9:44 AM Micah Galizia ***@***.***> wrote:
>
> Your samsung TV has EPG data!?
>
> Any chance you know where they're getting it? I'm reverse engineering
> the GEM app, and they don't have a guide.  CBC *does* have a guide,
> but its in HTML and I'd rather not use beautiful soup.
>
> About the slowness, I agree - it's slow. I am not 100% sure if I can
> improve on that since afaik, once I hand the stream over to Kodi it is
> out of my hands.
>
> On Tue, Aug 31, 2021 at 9:42 AM betatester3016 ***@***.***> wrote:
> >
> > Hi @micahg
> >
> > I tried on Nvidia Shield Pro and compared to the Samsung TV Plus and Pluto TV addons, the CBC addon takes longer to load the live stream via EPG.
> >
> > Samsung TV Plus addon load time: 1 sec
> > Pluto TV addon load time: 1 sec
> > CBC addon load time: 4 sec
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android.
>
>
>
> --
> "The mark of an immature man is that he wants to die nobly for a
> cause, while the mark of the mature man is that he wants to live
> humbly for one."   --W. Stekel



-- 
"The mark of an immature man is that he wants to die nobly for a
cause, while the mark of the mature man is that he wants to live
humbly for one."   --W. Stekel

**Comment by micahg** [comment] 2021-08-31 17:21
This was the best I could find:
https://www.cbc.ca/programguide/daily/2021/08/31/cbc_television/?t=1630430051837.

If you've got something better I'd love it.

On Tue, Aug 31, 2021 at 1:05 PM Micah Galizia ***@***.***> wrote:
>
> ... anyway... if you can find a json or xml cbc epg feed I'd integrate
> it *for sure*....
>
> On Tue, Aug 31, 2021 at 9:44 AM Micah Galizia ***@***.***> wrote:
> >
> > Your samsung TV has EPG data!?
> >
> > Any chance you know where they're getting it? I'm reverse engineering
> > the GEM app, and they don't have a guide.  CBC *does* have a guide,
> > but its in HTML and I'd rather not use beautiful soup.
> >
> > About the slowness, I agree - it's slow. I am not 100% sure if I can
> > improve on that since afaik, once I hand the stream over to Kodi it is
> > out of my hands.
> >
> > On Tue, Aug 31, 2021 at 9:42 AM betatester3016 ***@***.***> wrote:
> > >
> > > Hi @micahg
> > >
> > > I tried on Nvidia Shield Pro and compared to the Samsung TV Plus and Pluto TV addons, the CBC addon takes longer to load the live stream via EPG.
> > >
> > > Samsung TV Plus addon load time: 1 sec
> > > Pluto TV addon load time: 1 sec
> > > CBC addon load time: 4 sec
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> > > Triage notifications on the go with GitHub Mobile for iOS or Android.
> >
> >
> >
> > --
> > "The mark of an immature man is that he wants to die nobly for a
> > cause, while the mark of the mature man is that he wants to live
> > humbly for one."   --W. Stekel
>
>
>
> --
> "The mark of an immature man is that he wants to die nobly for a
> cause, while the mark of the mature man is that he wants to live
> humbly for one."   --W. Stekel



-- 
"The mark of an immature man is that he wants to die nobly for a
cause, while the mark of the mature man is that he wants to live
humbly for one."   --W. Stekel

**Comment by betatester3016** [comment] 2021-08-31 17:34
> Your samsung TV has EPG data!? Any chance you know where they're getting it? 
> […](#)

I would suggest reaching out to [Matt Huisman](https://github.com/matthuisman/slyguy.addons). He is very knowledgeable about this topic.

**Comment by micahg** [comment] 2021-08-31 17:54
Well, I imagine (given their github) that they might be able to advise on getting EPG data into Kodi, which I can already do in the addon. What we need is a good source, which I do not believe they will know.

**Comment by betatester3016** [comment] 2021-09-01 11:50
Hi @micahg 

The link to the program guide seems to be the only thing CBC has to offer. I found [this video](https://www.youtube.com/watch?v=RT7mtk4jNLs) but unsure if that will work with CBC.

**Comment by micahg** [comment] 2021-09-02 01:05
OK,

If you uinstall and reinstall you can now pick and choose which channels you want in your IPTV. Like for me, i would only want the local station + NN.  Channels are managed through context menus on the LIve Channels list.

**Comment by micahg** [comment] 2021-09-02 01:10
Also, playback response time should be improved as I'm now using inputstream properly (enable inputstream through your CBC addons settings).

**Comment by micahg** [comment] 2021-09-02 12:04
Yeah, I'll have a look at parsing the HTML guide at some point.

**Comment by betatester3016** [comment] 2021-09-04 02:43
I'll also see what I can figure out on my end in regards to HTML > EPG.

**Comment by micahg** [comment] 2021-09-09 16:27
OK, 4.0.9 has EPG. EPG loading is slow. I'm waiting to hear back if I can parallelize the outbound guide calls to speed things up, but for now, they're synchronous.

**Comment by micahg** [comment] 2021-09-09 17:47
@betatester3016  4.0.10 has EPG done concurrenty, which is a *lot* faster.

**Comment by betatester3016** [comment] 2021-09-11 12:06
@micahg  Sorry about the late reply. I was out of town for a family gathering. 

I tested 4.0.10 and it seems to be working fine. Good call on the option to include / exclude channels.

The only thing I noticed is that Olympic Channel remains empty, but that might be by design.  All other  channels populate the EPG. 

EPG creation is somewhat slower compared to the Samsung TV Plus addon. I find the speed acceptable because I understand that CBC's online program guide isn't exactly 'standard', and comes with its own, unique challenges. I just want you to be aware this is where you might get feedback from end-users.

But for that, I believe you nailed it with this version and have a release candidate.

The addon also nicely cooperates with Matt Huisman's [IPTV Merge](https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html) addon. I believe this to be a bonus.

![screenshot00003](https://user-images.githubusercontent.com/49594656/132946682-51a5cd03-d719-4bc2-a8f5-292a36e8a9d8.png)

**Comment by micahg** [comment] 2021-09-11 12:33
Oh, thanks for the heads up on IPTV merge - if it does what I think it does it'll save me having to write it myself.

Also, yeah, afaik there is no guide data for the Olympic channel.

**Comment by betatester3016** [comment] 2021-09-11 13:25
Please remember to have the CBC Addon listed as compatible with [IPTV Manager](https://github.com/add-ons/service.iptv.manager/wiki/Supported-Addons).

**Comment by micahg** [comment] 2021-09-11 15:09
I will, when the or in the main repo closes

**Comment by betatester3016** [comment] 2021-09-11 21:55
> I will, when the or in the main repo closes

@micahg  Do you mean the PR I submitted?

Will you also release a Leia version, or Matrix only? Reason I ask is because CoreELEC has decided that the Leia version (CE 9.x.x) is [EOL](https://discourse.coreelec.org/t/coreelec-9-leia-end-of-life-announcement/16684) the end of this year.

**Comment by micahg** [comment] 2021-09-11 21:57
https://github.com/xbmc/repo-plugins/pull/3716

**Comment by micahg** [comment] 2021-09-12 14:40
Merged into main kodi repo.
IPTV Manger wiki updated.

**Closed by micahg** 2021-09-12 14:40 UTC

**Comment by betatester3016** [comment] 2021-09-15 17:24
@micahg Thank you for all the time and effort you are putting into maintaining this addon.
